server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #  liquibase:
  #    enabled: true
  #    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
